### ISSUE TITLE
contract creation generates a null address in tx ID

### ISSUE THREAD

**Issue by cryptolarity** [gochain-io/explorer#112]
contract creation generates a null address where the contract address should be, i.e. - https://explorer.gochain.io/addr/0x4147f2dbc3c41d05950de2a8e0925855e422581e

**Comment by jmank88** [comment]
The 'to' field is literally null for a contract creation. IIRC the created contract address has to be pulled from the receipt, and we'll have to find a meaningful way of distinguishing those type of txs if we want to display it here - otherwise it can be displayed with the rest of the contract details https://explorer.gochain.io/tx/0x906f4456a09837dd434f968f88258b195f06942bc612a1971c241608fe536124

**Comment by jmank88** [comment]
#80

**Comment by inkberk** [comment]
closed in #162 by @r-kononov
