### ISSUE TITLE
Explorer Design Change

### ISSUE THREAD

**Issue by CoreytMayweather** [gochain-io/explorer#222]
Instead of 3 windows to scroll through '24 hours transactions' , ' 'last 7 days', ' all over transactions'

Why not just show a really fancy, elegant looking graph. 
[http://pixelsdaily.com/resources/photoshop/psds/psd-elegant-line-graph/
![image](https://user-images.githubusercontent.com/42082720/51815894-98be8f00-2289-11e9-9896-d713ebb3029f.png)](url)

Showing the increase in Transactions by the day to day basis?

**Comment by jmank88** [comment]
I'm not sure a line graph would make sense here - what would a point on the line represent?

A per-day bar graph could work, but not as a replacement for the existing stats because users would have to do math to figure out the 7-day value and all-time wouldn't be feasible at all.

A _cumulative_ line graph (only ever increases) of all txs to date might be useful, but still only supplemental - not as a replacement.

**Comment by CoreytMayweather** [comment]
Have the 3 windows replaced as a small rectangle widget atop the graph. The small rectangle widget would have the Overall Transactions to date. While the graph would just show a weekly, day by day of Transactions.

**Comment by jmank88** [comment]
A 'weekly, day by day' graph is not sufficient for replacing the existing stats. The '24hr' and 'last 7 days' stats are relative to a specific timestamp - not based on calendar days (not midnight-to-midnight).

**Comment by CoreytMayweather** [comment]
Ahhh ok, gotcha.
