### ISSUE TITLE
 Interact with a Smart Contract got error after veryfy sourcecode

### ISSUE THREAD

**Issue by dome** [gochain-io/explorer#329]
Reproduce
1. deploy smartcontract hello.sol
2. access function getmessage() 
 it's work fine
3.  verify sourcecode 
4. access function getmessage()
got error 
RROR: RETURNED VALUES AREN'T VALID, DID IT RUN OUT OF GAS?

**Comment by r-gochain** [comment]
Hmm, could you share the source code of the contract, because I was not able to reproduce

1) Deployed this contract - https://gist.github.com/r-gochain/df4f0c027004bd0454ef3b564ed0672c
2) Used contract (using wallet https://testnet-explorer.gochain.io/wallet)
3) Validate it https://testnet-explorer.gochain.io/addr/0xf53C4d10a494e53F8f9363dA1e34C1a898a3C4e1?addr_tab=contract_source
4) Used it again (it works)

![image](https://user-images.githubusercontent.com/40002763/60458904-7372ea00-9c48-11e9-8cc9-956c8ed015dd.png)

PS Feel free to use it (abi is in the same gist - https://gist.github.com/r-gochain/df4f0c027004bd0454ef3b564ed0672c)

**Comment by dome** [comment]
Please verify contract 
https://testnet-explorer.gochain.io/addr/0xf53C4d10a494e53F8f9363dA1e34C1a898a3C4e1?addr_tab=contract_source

**Comment by r-gochain** [comment]
@dome could you share the source code of the contract?

**Comment by dome** [comment]
pragma solidity ^0.5.0;
contract HelloWorld {
    function sayHello() public pure returns(string memory){
        return "hello world";
    }
}
